spring.application.name=CompetencyHub
logging.level.root=ERROR
logging.level.org.springframework=ERROR

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/competencyhub
spring.datasource.username=chub
spring.datasource.password=chub

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# See the SQL Hibernate actually runs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE