-- V10: login accounts, separate from the people they belong to.
--
-- app_user answers "who can log in, with what password, as what role". student and mentor
-- answer "who is this person in the learning domain". Keeping them apart means:
--   - an ADMIN is a login with no student or mentor profile at all;
--   - existing students (seeded before this migration) keep working without a login;
--   - changing how people authenticate later (Google, SSO) touches this table, not grading.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    -- Never the password: a one-way hash, with its algorithm prefix, e.g. "{bcrypt}$2a$10$...".
    -- 100 chars leaves room for the prefix and a stronger algorithm later.
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT chk_app_user_role CHECK (role IN ('ADMIN', 'MENTOR', 'STUDENT'))
);

-- One-to-one links from the domain people to their login. Nullable: a student row can exist
-- without an account (rows created before V10, or imported). UNIQUE makes it one-to-one --
-- without it, two students could share one login.
ALTER TABLE student ADD COLUMN user_id BIGINT UNIQUE REFERENCES app_user (id);
ALTER TABLE mentor  ADD COLUMN user_id BIGINT UNIQUE REFERENCES app_user (id);
