-- Audit trail for scheduled job executions.
--
-- Worth its own table rather than log lines, because "did the nightly job run last night?"
-- is a question you will ask at 9 AM when the numbers look wrong, and by then the container
-- that ran it has been replaced and its stdout is gone.
CREATE TABLE job_run (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name          VARCHAR(100) NOT NULL,
    started_at        TIMESTAMPTZ  NOT NULL,
    finished_at       TIMESTAMPTZ,
    status            VARCHAR(20)  NOT NULL,
    records_processed INT          NOT NULL DEFAULT 0,
    detail            TEXT
);

-- Supports "show me the last run of this job", which is the only query this table gets.
CREATE INDEX idx_job_run_name_started ON job_run (job_name, started_at DESC);

-- The computed result lives on the enrollment. Denormalized on purpose: it is read on every
-- enrollment listing and recomputed once a night, so paying for the join on every read to
-- avoid one nightly write is the wrong trade.
ALTER TABLE enrollment ADD COLUMN progress_percent INT NOT NULL DEFAULT 0;
ALTER TABLE enrollment ADD COLUMN progress_updated_at TIMESTAMPTZ;