-- The missing fact table: a student's attempt at an assessment, and what they scored.
--
-- Everything else in the schema up to now has been definitions (courses, competencies,
-- assessments) or relationships (enrollment). This is the first table that records something
-- a student actually DID, which is why nothing could be computed without it.
CREATE TABLE submission (
                            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            student_id    BIGINT    NOT NULL REFERENCES student(id),
                            assessment_id BIGINT    NOT NULL REFERENCES assessment(id),
                            score         INTEGER   NOT NULL,
                            submitted_at  TIMESTAMP NOT NULL,

    -- A student may resubmit, so (student, assessment) is deliberately NOT unique. Mastery
    -- asks "was there ever a passing score", which tolerates many rows per pair.
                            CONSTRAINT submission_score_non_negative CHECK (score >= 0)
);

-- The recalculation job's access path: every submission for one student. Without this it is a
-- sequential scan of the whole table once per enrollment, which is invisible at 4 rows and
-- fatal at 400,000.
CREATE INDEX idx_submission_student ON submission (student_id);
CREATE INDEX idx_submission_assessment ON submission (assessment_id);

-- Undo the V6 mistake. progress.percent_complete already existed for this exact number, so
-- enrollment.progress_percent was a second home for the same fact -- and two places holding
-- one number is how they drift apart.
--
-- V6 has already run, so it is frozen and cannot be edited. Corrections go forward in a new
-- migration. Same rule that bit you on the V1 checksum mismatch, now working in your favor:
-- the history stays truthful about what the schema looked like at each point.
ALTER TABLE enrollment DROP COLUMN progress_percent;
ALTER TABLE enrollment DROP COLUMN progress_updated_at;