-- V9: submissions become a lifecycle (SUBMITTED -> GRADED), mentors exist to grade them,
-- every assessment gets a passing score, and notifications can come from more than one
-- kind of event.
--
-- Every ALTER that adds a required column follows the same three steps V4 used:
-- add it nullable -> backfill existing rows -> then add NOT NULL. Skipping the middle step
-- fails on any database that already has rows, which is every database but a fresh one.

-- ---------------------------------------------------------------------------------------
-- 1. Mentors
-- ---------------------------------------------------------------------------------------
CREATE TABLE mentor (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(100) NOT NULL,
    last_name      VARCHAR(100) NOT NULL,
    email          VARCHAR(255) NOT NULL UNIQUE,
    specialization VARCHAR(200),
    joined_on      DATE         NOT NULL
);

-- ---------------------------------------------------------------------------------------
-- 2. passing_score moves UP from objective_assessment to assessment
--
-- Until now only objective tests had a pass mark, so only they could prove mastery. Once
-- performance tasks need one too, the column is common to every subtype -- and in JOINED
-- inheritance, common columns belong in the parent table. This is the "pull up field"
-- refactoring, done in SQL.
-- ---------------------------------------------------------------------------------------
ALTER TABLE assessment ADD COLUMN passing_score INT;

UPDATE assessment a
SET passing_score = oa.passing_score
FROM objective_assessment oa
WHERE oa.id = a.id;

-- Existing performance tasks never had a pass mark. 70% of their range is a guess, but an
-- explicit, documented one -- and a mentor can change it later. NULL is not an option: the
-- mastery query compares against this column.
UPDATE assessment
SET passing_score = min_score + CEIL((max_score - min_score) * 0.7)
WHERE passing_score IS NULL;

ALTER TABLE assessment ALTER COLUMN passing_score SET NOT NULL;
ALTER TABLE assessment ADD CONSTRAINT chk_assessment_passing_in_range
    CHECK (passing_score BETWEEN min_score AND max_score);

ALTER TABLE objective_assessment DROP COLUMN passing_score;

-- ---------------------------------------------------------------------------------------
-- 3. Submission lifecycle
-- ---------------------------------------------------------------------------------------

-- A performance task is SUBMITTED with no score until a mentor grades it.
ALTER TABLE submission ALTER COLUMN score DROP NOT NULL;

ALTER TABLE submission ADD COLUMN status VARCHAR(20);
-- Every existing row has a score, so every existing row is already graded.
UPDATE submission SET status = 'GRADED';
ALTER TABLE submission ALTER COLUMN status SET NOT NULL;

ALTER TABLE submission ADD COLUMN attempt_number INT;
-- Number existing attempts 1, 2, 3... per (student, assessment), oldest first.
-- row_number() OVER (PARTITION BY ...) restarts the count for each pair -- a window
-- function, which is how you number "within a group" in one statement.
UPDATE submission s
SET attempt_number = numbered.n
FROM (SELECT id,
             row_number() OVER (PARTITION BY student_id, assessment_id
                                ORDER BY submitted_at, id) AS n
      FROM submission) numbered
WHERE numbered.id = s.id;
ALTER TABLE submission ALTER COLUMN attempt_number SET NOT NULL;

ALTER TABLE submission ADD COLUMN content   TEXT;
ALTER TABLE submission ADD COLUMN feedback  TEXT;
ALTER TABLE submission ADD COLUMN graded_at TIMESTAMP;
UPDATE submission SET graded_at = submitted_at;   -- existing rows: graded when submitted

ALTER TABLE submission ADD COLUMN graded_by BIGINT REFERENCES mentor (id);

-- Optimistic locking, same mechanism as course.version: two mentors opening the same
-- submission cannot both grade it.
ALTER TABLE submission ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- One row per attempt. Two requests racing for "attempt 2" cannot both win.
ALTER TABLE submission ADD CONSTRAINT uq_submission_attempt
    UNIQUE (student_id, assessment_id, attempt_number);

-- The state machine, enforced by the database as well as the entity. A GRADED row must
-- have a score and a timestamp; a SUBMITTED row must not have a score yet.
ALTER TABLE submission ADD CONSTRAINT chk_submission_state CHECK (
    (status = 'SUBMITTED' AND score IS NULL     AND graded_at IS NULL)
 OR (status = 'GRADED'    AND score IS NOT NULL AND graded_at IS NOT NULL)
);

-- The mentor's grading queue: "ungraded submissions for this assessment".
CREATE INDEX idx_submission_assessment_status ON submission (assessment_id, status);

-- ---------------------------------------------------------------------------------------
-- 4. Notifications from more than one event type
--
-- source_event_id was UNIQUE on its own, and it held enrollment ids. Submission ids come
-- from a different sequence, so submission 5 and enrollment 5 would collide: the second
-- notification would be rejected as a "duplicate" of a message it has nothing to do with.
-- The id is only unique WITHIN an event type, so the key becomes the pair.
-- ---------------------------------------------------------------------------------------
ALTER TABLE notification ADD COLUMN event_type VARCHAR(50);
UPDATE notification SET event_type = 'ENROLLMENT_CREATED';
ALTER TABLE notification ALTER COLUMN event_type SET NOT NULL;

-- Postgres named the V5 inline UNIQUE constraint <table>_<column>_key.
ALTER TABLE notification DROP CONSTRAINT notification_source_event_id_key;
ALTER TABLE notification ADD CONSTRAINT uq_notification_event
    UNIQUE (event_type, source_event_id);
